name: safecell_venezuela
description: Safecell Venezuela - Repuestos y Accesorios para Móviles
publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.1
  go_router: ^13.2.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.5
  package_info_plus: ^8.0.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/banners/
    - assets/brands/
    - assets/categories/
    - assets/logos/
